from __future__ import annotations

import html
from pathlib import Path
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from agentfuzz.core.result import HarnessResult


_TEMPLATE = """<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8" />
<title>agentfuzz report</title>
<style>
  :root {{ color-scheme: light dark; }}
  body {{
    font: 14px/1.5 -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif;
    max-width: 980px; margin: 2rem auto; padding: 0 1rem;
  }}
  h1 {{ margin-bottom: 0.2rem; }}
  .sub {{ color: #888; margin-top: 0; }}
  .stat-grid {{
    display: grid; grid-template-columns: repeat(4, 1fr);
    gap: 1rem; margin: 1.5rem 0;
  }}
  .stat {{
    border: 1px solid #ddd3; border-radius: 8px; padding: 1rem;
  }}
  .stat .label {{ color: #888; font-size: 12px; text-transform: uppercase; letter-spacing: 0.05em; }}
  .stat .value {{ font-size: 28px; font-weight: 600; margin-top: 0.25rem; }}
  table {{ width: 100%; border-collapse: collapse; margin: 1rem 0; }}
  th, td {{ text-align: left; padding: 8px 12px; border-bottom: 1px solid #ddd3; }}
  th {{ font-size: 12px; text-transform: uppercase; letter-spacing: 0.05em; color: #888; }}
  .pass {{ color: #2a7; }} .fail {{ color: #c44; }}
  .bar {{ background: #ddd3; height: 6px; border-radius: 3px; overflow: hidden; }}
  .bar > i {{ display: block; height: 100%; background: #c44; }}
  details {{ margin: 1rem 0; }}
  summary {{ cursor: pointer; font-weight: 600; }}
  pre {{ background: #ddd3; padding: 0.8rem; border-radius: 6px; overflow-x: auto; }}
  .badge {{
    display: inline-block; padding: 1px 8px; border-radius: 10px;
    background: #ddd3; font-size: 12px; margin-right: 4px;
  }}
</style>
</head>
<body>
<h1>agentfuzz report</h1>
<p class="sub">{n_total} iterations · {n_faults} active faults</p>

<div class="stat-grid">
  <div class="stat"><div class="label">Pass rate</div><div class="value">{pass_rate}</div></div>
  <div class="stat"><div class="label">Passed</div><div class="value pass">{n_passed}</div></div>
  <div class="stat"><div class="label">Failed</div><div class="value fail">{n_failed}</div></div>
  <div class="stat"><div class="label">Total tokens</div><div class="value">{total_tokens}</div></div>
</div>

<h2>Failures by fault</h2>
{failures_table}

<h2>Failures by tag</h2>
{tags_table}

<h2>Iterations</h2>
{iterations_table}

<p class="sub">Generated by <a href="https://github.com/SubhashPavan/agentfuzz">agentfuzz</a>.</p>
</body>
</html>
"""


def _kv_table(title_left: str, title_right: str, items: dict[str, int]) -> str:
    if not items:
        return "<p><em>None.</em></p>"
    total = max(items.values())
    rows = []
    for k, v in sorted(items.items(), key=lambda kv: -kv[1]):
        pct = v / total
        key = html.escape(k)
        rows.append(
            f"<tr><td>{key}</td><td>{v}</td>"
            f"<td><div class='bar'><i style='width:{pct:.0%}'></i></div></td></tr>"
        )
    return (
        f"<table><thead><tr><th>{title_left}</th><th>{title_right}</th><th></th></tr></thead>"
        f"<tbody>{''.join(rows)}</tbody></table>"
    )


def _iterations_table(result: HarnessResult) -> str:
    rows = []
    for it in result.iterations:
        cls = "pass" if it.passed else "fail"
        label = "PASS" if it.passed else "FAIL"
        tags = "".join(f"<span class='badge'>{html.escape(t)}</span>" for t in sorted(it.tags))
        reason = html.escape(it.failure_reason or "")
        rows.append(
            f"<tr><td>{it.iteration}</td><td class='{cls}'>{label}</td>"
            f"<td>{it.duration_ms:.0f} ms</td><td>{it.token_usage}</td>"
            f"<td>{tags}</td><td>{reason}</td></tr>"
        )
    return (
        "<table><thead><tr><th>#</th><th>Result</th><th>Duration</th>"
        "<th>Tokens</th><th>Tags</th><th>Failure reason</th></tr></thead>"
        f"<tbody>{''.join(rows)}</tbody></table>"
    )


def render_html_report(result: HarnessResult, path: Path) -> Path:
    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)
    body = _TEMPLATE.format(
        n_total=result.total,
        n_passed=result.passed,
        n_failed=result.failed,
        n_faults=len(result.fault_names),
        pass_rate=f"{result.pass_rate:.0%}",
        total_tokens=sum(i.token_usage for i in result.iterations),
        failures_table=_kv_table("Fault", "Failures", result.failures_by_fault()),
        tags_table=_kv_table("Tag", "Count", result.failures_by_tag()),
        iterations_table=_iterations_table(result),
    )
    path.write_text(body, encoding="utf-8")
    return path
